### ISSUE TITLE
ProtocolException with iOS .NET 6.0 Application: The number of bytes available is inconsistent with the HTTP Content-Length header.

### ISSUE THREAD

**Issue by chamons** [dotnet/wcf#4903]

**Comment by danmoseley** [comment]
I think this belongs in dotnet/wcf

**Comment by DuncWatts** [comment]
Note this works fine in a .NET 6 WPF application, it's only the .NET 6 iOS build that has this issue so far. I've yet to try it on Android or MacOS.

**Comment by danmoseley** [comment]
cc @radical @steveisok since this may be iOS specific and therefore not a WCF issue - perhaps they have seen something similar.

**Comment by chamons** [comment]
Given the lack of any Xamarin iOS types in the stack is the reason I bounced it over to the runtime at first.

**Comment by chamons** [comment]
I just checked, and this works fine on macOS Desktop with NET6.

**Comment by chamons** [comment]
[This](https://github.com/dotnet/wcf/blob/main/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpResponseMessageHelper.cs#L218-L228) appears to be the location of the exception.

**Comment by steveisok** [comment]
@simonrozsival Please give this a look and see if you can find anything.

**Comment by simonrozsival** [comment]
I managed to reproduce the issue locally. When the exception that @chamons pointed out is throw, the state is:
- `bytesRead == 0`
- `_contentLength == 348`
- `offset == 325`
- `count == 23`
- `buffer` contains 325 bytes corresponding to a UTF-8 encoded string `<?xml version="1.0" encoding="utf-8"?><soap:Envelope ...</soap:Envelope>`

The raw HTTP response is:

```yaml
HTTP/1.1 200 OK
Cache-Control: private, max-age=0
Content-Type: text/xml; charset=utf-8
Content-Encoding: gzip
Vary: Accept-Encoding
Server: Microsoft-IIS/10.0
X-AspNet-Version: 2.0.50727
X-Powered-By: ASP.NET
X-Powered-By-Plesk: PleskWin
Date: Thu, 08 Sep 2022 07:57:57 GMT
Content-Length: 348

<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><AddResponse xmlns="http://tempuri.org/"><AddResult>3</AddResult></AddResponse></soap:Body></soap:Envelope>
```
As far as I can tell the actual size of the body is 325 bytes. I think the `ProtocolException` is the correct behavior in this case because the server responded with incorrect `Content-Length` (even though it is not consistent with legacy Xamarin which seems to ignore this mismatch). The code in WCF that checks the mismatch is  7 years old and the `ReadAsync` code in `NSUrlSessionHandler+NSUrlSessionDataTaskStream` hasn't changed in 4 years so this doesn't seem like a recent regression.

@chamons can you share the macOS desktop project so I can try to check why that behaves differently?
